import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/*
          Блокирующий <script> с telegram.org был единственной точкой отказа
          всей страницы: пока он грузится, браузер не парсит документ, а если
          домен режет провайдер — пользователь смотрит в белый экран, пока
          запрос не отвалится по таймауту. Грузим асинхронно; страница
          рисуется сразу, а page.tsx дожидается window.Telegram опросом с
          дедлайном и умеет внятно сказать, что SDK так и не приехал.
        */}
        <script async src="https://telegram.org/js/telegram-web-app.js" />
      </head>
      <body className="min-h-full flex flex-col overflow-x-hidden">{children}</body>
    </html>
  );
}
